version: '3.3'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    ports:
      - 3000:3000

  evil-server:
    build:
      context: ./evil-server
      dockerfile: Dockerfile
    container_name: evil-server
    ports:
      - 3001:3001